### ISSUE TITLE
Question: How to add Layers from WMS request

### ISSUE THREAD

**Issue by NenkoPakov** [Esri/arcgis-runtime-demos-dotnet#39]
Hi, can you give me guidelines how to create Xamarin mobile app with map and to add on it two layers from this "http://anta.nat.bg:8080/cgi-bin/mapserv.exe?map=/ms4w/maps/map.map&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=bnd_lines,ot&STYLES=&SRS=EPSG:7801&BBOX=320471,4724240,323127,4730190&WIDTH=400&HEIGHT=300&FORMAT=image/png"
request.
I am new in programming and can't do it for days.
Many thanks!

**Comment by mbranscomb** [comment]
@NenkoPakov The [Esri Community](https://community.esri.com/community/developers/native-app-developers/arcgis-runtime-sdk-for-net) is the best place for questions.
